#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright © 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Author: Tencent AI Arena Authors
"""

from kaiwudrl.common.monitor.monitor_config_builder import MonitorConfigBuilder


def build_monitor():
    """
    # This function is used to create monitoring panel configurations for custom indicators.
    # 该函数用于创建自定义指标的监控面板配置。
    #
    # Note: this builder keeps algorithm-only metrics (loss-series, rollout aggregates)
    # plus locomotion reward panels aligned with ``train_env_conf_standard_locomotion.toml``.
    # Project-side defaults may also define ``reward_*`` panels; if merged dashboards show
    # duplicate names, dedupe in deployment yaml or trim one side.
    #
    # 注意：本 builder 保留算法独有指标（loss、滚动统计），并补充标准 locomotion 配置中的
    # ``reward_*`` 面板。若与项目侧 yaml 合并后出现同名指标，可在部署侧去重或删减一侧。
    #
    # Extra DIY-only panels: constrained-PPO / NP3O-style losses and rollout stats from
    # ``agent_diy/algorithm/algorithm.py`` and ``agent_diy/workflow/train_workflow.py``.
    # 额外 DIY 面板：约束 PPO 损失与 workflow 滚动统计，便于观察收敛与安全约束。
    #
    # Locomotion reward panels below mirror ``train_env_conf_standard_locomotion.toml``
    # episode sums (``reward_<term>``). Add panels here so NP3O-aligned tuning is
    # visible even when project-side yaml defaults are absent or merged differently.
    # 下方 locomotion 奖励面板与标准配置中的回合汇总 ``reward_<term>`` 对齐；
    # 便于在无默认 yaml 或合并顺序不同时仍能观察 NP3O 风格调参。

    Returns:
        dict: monitor configuration dictionary
        返回值：监控配置字典
    """
    monitor = MonitorConfigBuilder()

    config_dict = (
        monitor.title("四足机器人导航")
        # ==============================================================
        # Group 1: Algorithm training loss metrics (unique to this builder, not covered by yaml)
        # Group 1: 算法训练损失指标（本 builder 独有，yaml 未覆盖）
        # ==============================================================
        .add_group(
            group_name="算法指标",
            group_name_en="algorithm",
        )
        .add_panel(
            name="总损失",
            name_en="total_loss",
            type="line",
        )
        .add_metric(
            metrics_name="total_loss",
            expr="avg(total_loss{})",
        )
        .end_panel()
        .add_panel(
            name="价值损失",
            name_en="value_loss",
            type="line",
        )
        .add_metric(
            metrics_name="value_loss",
            expr="avg(value_loss{})",
        )
        .end_panel()
        .add_panel(
            name="策略损失",
            name_en="policy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="policy_loss",
            expr="avg(policy_loss{})",
        )
        .end_panel()
        .add_panel(
            name="熵损失",
            name_en="entropy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="entropy_loss",
            expr="avg(entropy_loss{})",
        )
        .end_panel()
        .add_panel(
            name="代价价值损失",
            name_en="cost_value_loss",
            type="line",
        )
        .add_metric(
            metrics_name="cost_value_loss",
            expr="avg(cost_value_loss{})",
        )
        .end_panel()
        .add_panel(
            name="约束违反损失",
            name_en="violation_loss",
            type="line",
        )
        .add_metric(
            metrics_name="violation_loss",
            expr="avg(violation_loss{})",
        )
        .end_panel()
        .add_panel(
            name="学习率",
            name_en="learning_rate",
            type="line",
        )
        .add_metric(
            metrics_name="learning_rate",
            expr="avg(learning_rate{})",
        )
        .end_panel()
        .end_group()
        # ==============================================================
        # Group 2: Constrained PPO / cost signals (algorithm.learn)
        # Group 2: 约束与代价信号（算法更新）
        # ==============================================================
        .add_group(
            group_name="约束与代价",
            group_name_en="constraint_cost",
        )
        .add_panel(
            name="代价优势均值",
            name_en="mean_cost",
            type="line",
        )
        .add_metric(
            metrics_name="mean_cost",
            expr="avg(mean_cost{})",
        )
        .end_panel()
        .add_panel(
            name="代价回报均值",
            name_en="cost_return_mean",
            type="line",
        )
        .add_metric(
            metrics_name="cost_return_mean",
            expr="avg(cost_return_mean{})",
        )
        .end_panel()
        .add_panel(
            name="原始违反均值",
            name_en="raw_mean_violation",
            type="line",
        )
        .add_metric(
            metrics_name="raw_mean_violation",
            expr="avg(raw_mean_violation{})",
        )
        .end_panel()
        .add_panel(
            name="正违反均值",
            name_en="positive_mean_violation",
            type="line",
        )
        .add_metric(
            metrics_name="positive_mean_violation",
            expr="avg(positive_mean_violation{})",
        )
        .end_panel()
        .add_panel(
            name="惩罚系数均值",
            name_en="k_value_mean",
            type="line",
        )
        .add_metric(
            metrics_name="k_value_mean",
            expr="avg(k_value_mean{})",
        )
        .end_panel()
        .add_panel(
            name="惩罚系数最大值",
            name_en="k_value_max",
            type="line",
        )
        .add_metric(
            metrics_name="k_value_max",
            expr="avg(k_value_max{})",
        )
        .end_panel()
        .end_group()
        # ==============================================================
        # Group 3: Rollout / episode aggregates (train_workflow, ~60s report)
        # Group 3: 滚动与回合汇总（workflow 约每分钟上报）
        # ==============================================================
        .add_group(
            group_name="滚动统计",
            group_name_en="rollout",
        )
        .add_panel(
            name="训练回合计数",
            name_en="episode_cnt",
            type="line",
        )
        .add_metric(
            metrics_name="episode_cnt",
            expr="avg(episode_cnt{})",
        )
        .end_panel()
        .add_panel(
            name="单局奖励合计",
            name_en="episode_reward",
            type="line",
        )
        .add_metric(
            metrics_name="episode_reward",
            expr="avg(episode_reward{})",
        )
        .end_panel()
        .add_panel(
            name="步级奖励均值",
            name_en="reward_mean",
            type="line",
        )
        .add_metric(
            metrics_name="reward_mean",
            expr="avg(reward_mean{})",
        )
        .end_panel()
        .add_panel(
            name="步级奖励标准差",
            name_en="reward_std",
            type="line",
        )
        .add_metric(
            metrics_name="reward_std",
            expr="avg(reward_std{})",
        )
        .end_panel()
        .add_panel(
            name="步级代价均值",
            name_en="cost_mean",
            type="line",
        )
        .add_metric(
            metrics_name="cost_mean",
            expr="avg(cost_mean{})",
        )
        .end_panel()
        .add_panel(
            name="代价违反均值",
            name_en="violation_mean",
            type="line",
        )
        .add_metric(
            metrics_name="violation_mean",
            expr="avg(violation_mean{})",
        )
        .end_panel()
        .add_panel(
            name="代价来源编码",
            name_en="cost_source_id",
            type="line",
        )
        .add_metric(
            metrics_name="cost_source_id",
            expr="avg(cost_source_id{})",
        )
        .end_panel()
        .end_group()
        # ==============================================================
        # Group 4–8: Locomotion reward episode means (standard_locomotion.toml)
        # Group 4–8：标准 locomotion 奖励回合均值（与 TOML 中启用的项对应）
        # ==============================================================
        .add_group(
            group_name="奖励速度跟踪",
            group_name_en="reward_tracking",
        )
        .add_panel(
            name="线速度跟踪奖励",
            name_en="reward_track_lin_vel_xy",
            type="line",
        )
        .add_metric(
            metrics_name="reward_track_lin_vel_xy",
            expr="avg(reward_track_lin_vel_xy{})",
        )
        .end_panel()
        .add_panel(
            name="角速度跟踪奖励",
            name_en="reward_track_ang_vel_z",
            type="line",
        )
        .add_metric(
            metrics_name="reward_track_ang_vel_z",
            expr="avg(reward_track_ang_vel_z{})",
        )
        .end_panel()
        .add_panel(
            name="前向速度密集奖励",
            name_en="reward_forward_velocity",
            type="line",
        )
        .add_metric(
            metrics_name="reward_forward_velocity",
            expr="avg(reward_forward_velocity{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="奖励姿态与上坡",
            group_name_en="reward_posture_uphill",
        )
        .add_panel(
            name="线速度Z惩罚直立门控",
            name_en="reward_lin_vel_z_up",
            type="line",
        )
        .add_metric(
            metrics_name="reward_lin_vel_z_up",
            expr="avg(reward_lin_vel_z_up{})",
        )
        .end_panel()
        .add_panel(
            name="角速度XY惩罚直立门控",
            name_en="reward_ang_vel_xy_up",
            type="line",
        )
        .add_metric(
            metrics_name="reward_ang_vel_xy_up",
            expr="avg(reward_ang_vel_xy_up{})",
        )
        .end_panel()
        .add_panel(
            name="姿态偏离惩罚直立门控",
            name_en="reward_orientation_up",
            type="line",
        )
        .add_metric(
            metrics_name="reward_orientation_up",
            expr="avg(reward_orientation_up{})",
        )
        .end_panel()
        .add_panel(
            name="上坡正向激励",
            name_en="reward_upward",
            type="line",
        )
        .add_metric(
            metrics_name="reward_upward",
            expr="avg(reward_upward{})",
        )
        .end_panel()
        .add_panel(
            name="基座高度跟踪惩罚",
            name_en="reward_correct_base_height",
            type="line",
        )
        .add_metric(
            metrics_name="reward_correct_base_height",
            expr="avg(reward_correct_base_height{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="奖励步态与楼梯",
            group_name_en="reward_gait_stairs",
        )
        .add_panel(
            name="脚部滞空时间奖励",
            name_en="reward_feet_air_time",
            type="line",
        )
        .add_metric(
            metrics_name="reward_feet_air_time",
            expr="avg(reward_feet_air_time{})",
        )
        .end_panel()
        .add_panel(
            name="髋关节回默认惩罚",
            name_en="reward_hip_to_default",
            type="line",
        )
        .add_metric(
            metrics_name="reward_hip_to_default",
            expr="avg(reward_hip_to_default{})",
        )
        .end_panel()
        .add_panel(
            name="摆动腿高度惩罚楼梯",
            name_en="reward_feet_height_body",
            type="line",
        )
        .add_metric(
            metrics_name="reward_feet_height_body",
            expr="avg(reward_feet_height_body{})",
        )
        .end_panel()
        .add_panel(
            name="对角腿镜像惩罚",
            name_en="reward_foot_mirror_up",
            type="line",
        )
        .add_metric(
            metrics_name="reward_foot_mirror_up",
            expr="avg(reward_foot_mirror_up{})",
        )
        .end_panel()
        .add_panel(
            name="移动期少于两足触地惩罚",
            name_en="reward_no_fly",
            type="line",
        )
        .add_metric(
            metrics_name="reward_no_fly",
            expr="avg(reward_no_fly{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="奖励能耗与平滑",
            group_name_en="reward_energy_smooth",
        )
        .add_panel(
            name="能耗惩罚",
            name_en="reward_energy",
            type="line",
        )
        .add_metric(
            metrics_name="reward_energy",
            expr="avg(reward_energy{})",
        )
        .end_panel()
        .add_panel(
            name="动作二阶平滑惩罚",
            name_en="reward_action_smoothness",
            type="line",
        )
        .add_metric(
            metrics_name="reward_action_smoothness",
            expr="avg(reward_action_smoothness{})",
        )
        .end_panel()
        .add_panel(
            name="脚部接触力惩罚",
            name_en="reward_feet_contact_forces",
            type="line",
        )
        .add_metric(
            metrics_name="reward_feet_contact_forces",
            expr="avg(reward_feet_contact_forces{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="奖励关节与其他",
            group_name_en="reward_joint_misc",
        )
        .add_panel(
            name="关节加速度惩罚",
            name_en="reward_joint_acc",
            type="line",
        )
        .add_metric(
            metrics_name="reward_joint_acc",
            expr="avg(reward_joint_acc{})",
        )
        .end_panel()
        .add_panel(
            name="关节扭矩惩罚",
            name_en="reward_joint_torques",
            type="line",
        )
        .add_metric(
            metrics_name="reward_joint_torques",
            expr="avg(reward_joint_torques{})",
        )
        .end_panel()
        .add_panel(
            name="关节位置极限惩罚",
            name_en="reward_dof_pos_limits",
            type="line",
        )
        .add_metric(
            metrics_name="reward_dof_pos_limits",
            expr="avg(reward_dof_pos_limits{})",
        )
        .end_panel()
        .add_panel(
            name="动作变化率惩罚",
            name_en="reward_action_rate",
            type="line",
        )
        .add_metric(
            metrics_name="reward_action_rate",
            expr="avg(reward_action_rate{})",
        )
        .end_panel()
        .add_panel(
            name="非期望接触惩罚",
            name_en="reward_undesired_contacts",
            type="line",
        )
        .add_metric(
            metrics_name="reward_undesired_contacts",
            expr="avg(reward_undesired_contacts{})",
        )
        .end_panel()
        .add_panel(
            name="终止惩罚",
            name_en="reward_termination",
            type="line",
        )
        .add_metric(
            metrics_name="reward_termination",
            expr="avg(reward_termination{})",
        )
        .end_panel()
        .add_panel(
            name="到达目标奖励",
            name_en="reward_reach_goal",
            type="line",
        )
        .add_metric(
            metrics_name="reward_reach_goal",
            expr="avg(reward_reach_goal{})",
        )
        .end_panel()
        .add_panel(
            name="静止期四足接触奖励",
            name_en="reward_has_contact",
            type="line",
        )
        .add_metric(
            metrics_name="reward_has_contact",
            expr="avg(reward_has_contact{})",
        )
        .end_panel()
        .add_panel(
            name="静止姿态回中惩罚",
            name_en="reward_stand_nice",
            type="line",
        )
        .add_metric(
            metrics_name="reward_stand_nice",
            expr="avg(reward_stand_nice{})",
        )
        .end_panel()
        .end_group()
        .build()
    )
    return config_dict
